import { 
  LayoutDashboard, 
  Users, 
  Calendar, 
  BookOpen, 
  FileClock, 
  UserCheck, 
  Settings, 
  LogOut, 
  Plus,
  Search,
  AlertCircle,
  CheckCircle,
  XCircle,
  Printer,
  GraduationCap,
  Pencil,
  Trash2,
  Clock,
  ChevronLeft,
  ChevronRight,
  PanelLeftClose,
  PanelLeftOpen,
  Copy,
  ListFilter,
  ArrowUpDown,
  Download
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Teachers: Users,
  Schedule: Calendar,
  Subjects: BookOpen,
  Leaves: FileClock,
  Substitutes: UserCheck,
  Classes: GraduationCap,
  Settings: Settings,
  Logout: LogOut,
  Add: Plus,
  Search: Search,
  Alert: AlertCircle,
  Check: CheckCircle,
  Reject: XCircle,
  Print: Printer,
  Edit: Pencil,
  Delete: Trash2,
  TimeSlots: Clock,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  SidebarOpen: PanelLeftOpen,
  SidebarClose: PanelLeftClose,
  Copy: Copy,
  Filter: ListFilter,
  Sort: ArrowUpDown,
  Download: Download
};